spring:
  datasource:
    url: jdbc:mysql://localhost/jsrdev_api_test?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 123456


## Para usar la DB en memoria configurar lo siguiente:
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password

## No olvidar borrar la anotacion @AutoConfigureTestDatabase en la clase de prueba MedicRepositoryTest